/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ActivatedPluginInfo {
  id: string
  name: string
  version: string
  description?: string
  bundleDir: string
  sidebarPanels: Array<SidebarPanelInfo>
  logs: Array<PluginLogEntry>
  activation: ActivationInfo
  requiredPermissions: Array<string>
  optionalPermissions: Array<string>
  grantedPermissions: Array<string>
  pendingPermissions: Array<string>
}

/**
 * Activates a previously loaded plugin. Spawns the wasmtime Store,
 * links the host imports, runs the plugin's `activate()` export,
 * captures contributed sidebar panels + emitted logs.
 */
export declare function activatePlugin(pluginId: string): Promise<ActivatedPluginInfo>

/**
 * Emits a topic to every subscribed plugin, reporting failures to the
 * supervisor. Resolves with one entry per subscriber:
 * `{ pluginId, status, detail, disabled }`.
 *
 * A plugin trapping on an event must not fail the request that
 * produced it, so failures are reported rather than thrown.
 */
export declare function emitEvent(topic: string, payload: string): Promise<Array<{
  pluginId: string
  status: 'delivered' | 'notInstantiated' | 'closed' | 'failed'
  /**
   * Why a `failed` delivery failed. `deadline` means the plugin ran
   * past its time budget and the host interrupted it; `trapped` means
   * the guest itself faulted; `host` means the failure was on our side
   * of the boundary. `null` unless `status` is `failed`.
   */
  reason: 'deadline' | 'trapped' | 'host' | null
  /** The full error chain, including the wasm backtrace. */
  detail: string | null
  disabled: boolean
}>>

export interface ActivationInfo {
  status: string
  message?: string
}

/**
 * Clears the per-call session identifier for the named plugin.
 * Always called after a plugin invocation completes (success or
 * error) to prevent leakage into the next caller's context.
 */
export declare function clearCallContext(pluginId: string): Promise<void>

/**
 * Drops the plugin's registry entry, releasing the wasmtime Store and
 * staged bundle. Subsequent `activatePlugin` calls require a fresh
 * `loadPlugin` to re-stage.
 */
export declare function deactivatePlugin(pluginId: string): Promise<void>

/**
 * Persists an optional-permission grant on the plugin's registry
 * entry. No-op when already granted. Returns the updated activated
 * view so callers can refresh their cached UI state.
 */
export declare function grantPermission(pluginId: string, permission: string): Promise<void>

/**
 * Initialises the global `tracing` subscriber for the Node process.
 * Idempotent: subsequent calls return `"already_initialised"`.
 */
export declare function initTracing(): string

/**
 * Snapshot of every currently active plugin. Cheap clone of in-memory
 * state; safe to call from any Fastify request handler.
 */
export declare function listActive(): Promise<Array<ActivatedPluginInfo>>

/**
 * Loads a plugin bundle from disk. Validates the manifest, compiles
 * the WASM component, registers the plugin in the process-wide
 * registry, and returns a snapshot of staged-plugin metadata.
 */
export declare function loadPlugin(bundlePath: string): Promise<StagedPluginInfo>

/** Returns a static pong string. Smoke test that the binding loaded. */
export declare function ping(): string

export interface PluginLogEntry {
  level: string
  message: string
}

/**
 * Atomically reloads a plugin from its on-disk bundle without
 * requiring a shell restart. Captures the bundle path from the
 * current registry entry, deactivates the existing instance (drops
 * the wasmtime Store, freeing memory), re-stages from disk, and
 * re-activates.
 *
 * Used by `POST /api/plugins/:id/reload` to pick up bundle changes
 * (manifest edits, fresh `ui.mjs` after a plugin author's `pnpm
 * build`, etc.) without restarting the host. The reload is **not
 * transactional** — if the re-stage fails after the deactivate, the
 * plugin is left unloaded, surfaced as a normal load error to the
 * caller. The next call to `loadPlugin` (or another `reloadPlugin`
 * attempt) puts it back.
 */
export declare function reloadPlugin(pluginId: string): Promise<ActivatedPluginInfo>

/**
 * Revokes a previously granted optional permission. No-op when the
 * permission was not granted.
 */
export declare function revokePermission(pluginId: string, permission: string): Promise<void>

/**
 * Sets the calling session identifier for the named plugin's next
 * invocation. Multi-tenant Fastify handlers call this before invoking
 * any plugin-side function so host imports such as
 * `db.current-session()` reflect the caller's session, not a value
 * baked in at activation time.
 *
 * Always pair with `clearCallContext` (or call `setCallContext` again
 * for the next caller); leaving stale context risks one session
 * seeing another's identifier on a subsequent unrelated call.
 */
export declare function setCallContext(pluginId: string, sessionId: string): Promise<void>

export interface SidebarPanelInfo {
  id: string
  label: string
  icon?: string
}

export interface StagedPluginInfo {
  id: string
  name: string
  version: string
  description?: string
  world: string
  targets: Array<string>
  restartPolicy: string
  /**
   * Absolute path to the plugin's on-disk bundle directory. Server
   * route handlers use this to resolve `<bundle>/ui.mjs` for the
   * `GET /api/plugins/:id/ui.mjs` endpoint (I2.5) without going
   * through a NAPI hop per request.
   */
  bundleDir: string
  requiredPermissions: Array<string>
  optionalPermissions: Array<string>
}
