/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function close(sessionId: string): Promise<void>

/**
 * Switches a session between autocommit and manual commit. Omit
 * `config` to keep the session's current transaction settings.
 * Rejects while a transaction is open.
 */
export declare function setTransactionMode(sessionId: string, mode: unknown, config?: unknown): Promise<any>

/** Opens an explicit transaction. Manual mode opens one on the first statement. */
export declare function beginTransaction(sessionId: string): Promise<any>

/** Commits the open transaction. */
export declare function commitTransaction(sessionId: string): Promise<any>

/** Rolls back the open transaction, discarding every statement since it opened. */
export declare function rollbackTransaction(sessionId: string): Promise<any>

/** Current transaction state; answered without touching the engine. */
export declare function transactionStatus(sessionId: string): Promise<any>

export declare function connect(config: ConnectionConfig): Promise<ConnectionHandle>

/**
 * Connection configuration mirrored from [`plamenix_db::ConnectionConfig`].
 *
 * Field names use `camelCase` on the JS side; `serde` keeps the Rust
 * names. The two representations stay in sync because `From<JsConfig>`
 * performs the rename explicitly.
 */
export interface ConnectionConfig {
  host: string
  port: number
  database: string
  user: string
  password: string
  encryptionKey?: string
  fbclientPath?: string
  charset?: string
  encryptionRequired: boolean
  pureRust?: boolean
  embedded?: boolean
}

export interface ConnectionHandle {
  sessionId: string
}

export declare function cryptState(sessionId: string): Promise<string>

export declare function databaseStats(sessionId: string): Promise<any>

export declare function describeSchema(sessionId: string): Promise<any>

export declare function execute(sessionId: string, sql: string): Promise<any>

/**
 * Splits `sql` into statements, applies the per-statement row cap to
 * SELECT-like queries, executes each in order, and returns one
 * [`StatementOutcome`] per parsed statement. Aborts after the first
 * failure (mirroring the Tauri command).
 */
export declare function executeBatch(sessionId: string, sql: string): Promise<any>

/**
 * Runs the export pipeline server-side: executes one or more SELECTs,
 * then builds a CSV / JSON / SQL / XML deliverable using the shared
 * `plamenix-db::export` formatters. Returns the full text. The
 * HTTP route on top is responsible for chunked transfer to the
 * client.
 */
export declare function exportQuery(sessionId: string, format: string, csvDelimiter: string, scopeJson: string, includeDdl?: boolean | undefined | null): Promise<string>

export declare function fetchBlob(sessionId: string, blobId: string): Promise<string>

/**
 * Initialises the global `tracing` subscriber for the Node process.
 *
 * Idempotent: subsequent calls return `"already_initialised"` without
 * touching the subscriber. The OTLP exporter only attaches when the
 * `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable is set; otherwise
 * only the fmt layer is installed.
 *
 * Returns a short status string for the caller to log:
 * - `"fmt_only"` — fmt layer attached, no OTLP exporter.
 * - `"otlp:<endpoint>"` — OTLP exporter attached, shipping to endpoint.
 * - `"already_initialised"` — a previous call installed the subscriber.
 */
export declare function initTracing(): string

/**
 * Reads the host's `databases.conf` (when one is found at a known
 * install path) and returns the simple-form alias entries declared in
 * it. When no candidate file exists, returns an empty list with
 * `sourcePath = null`.
 */
export declare function listAliases(): any

/** Returns a static pong string. Smoke test that the binding loaded. */
export declare function ping(): string

export interface PingResult {
  engineVersion: string
}

export declare function pingSession(sessionId: string): Promise<PingResult>

/**
 * Tries to attach with the supplied configuration, fetches the engine
 * version, then closes the session. Always resolves with a structured
 * result (no thrown error on a clean failure); the `ok` flag tells the
 * caller whether the attempt succeeded.
 */
export declare function testConnection(config: ConnectionConfig): Promise<any>
