/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function close(sessionId: string): Promise<void>

export declare function connect(config: ConnectionConfig): Promise<ConnectionHandle>

/**
 * Connection configuration mirrored from [`plamenix_db::ConnectionConfig`].
 *
 * Field names use `camelCase` on the JS side; `serde` keeps the Rust
 * names. The two representations stay in sync because `From<JsConfig>`
 * performs the rename explicitly.
 */
export interface ConnectionConfig {
  host: string
  port: number
  database: string
  user: string
  password: string
  encryptionKey?: string
  fbclientPath?: string
  encryptionRequired: boolean
  pureRust?: boolean
}

export interface ConnectionHandle {
  sessionId: string
}

export declare function execute(sessionId: string, sql: string): Promise<any>

/** Returns a static pong string. Smoke test that the binding loaded. */
export declare function ping(): string

export interface PingResult {
  engineVersion: string
}

export declare function pingSession(sessionId: string): Promise<PingResult>
