/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ActivatedPluginInfo {
  id: string
  name: string
  version: string
  description?: string
  bundleDir: string
  sidebarPanels: Array<SidebarPanelInfo>
  logs: Array<PluginLogEntry>
  activation: ActivationInfo
  requiredPermissions: Array<string>
  optionalPermissions: Array<string>
  grantedPermissions: Array<string>
  pendingPermissions: Array<string>
}

/**
 * Activates a previously loaded plugin. Spawns the wasmtime Store,
 * links the host imports, runs the plugin's `activate()` export,
 * captures contributed sidebar panels + emitted logs.
 */
export declare function activatePlugin(pluginId: string): Promise<ActivatedPluginInfo>

export interface ActivationInfo {
  status: string
  message?: string
}

/**
 * Reads recent audit entries, newest first.
 *
 * A log nobody can read is a log nobody keeps. This is what makes the
 * table answerable without opening the file in another tool — though
 * it is a Firebird database, so opening it in Plamenix works too.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function auditRecent(limit?: number | undefined | null): Promise<any>

/**
 * Appends one entry to the audit log.
 *
 * # Errors
 *
 * When the metadata database cannot be reached. Callers on a request
 * path should log and continue: an unwritable audit log is worth
 * knowing about and is not worth refusing to serve over, or a full
 * disk becomes a denial of service.
 */
export declare function auditRecord(action: string, outcome: string, actor?: string | undefined | null, remoteAddr?: string | undefined | null, target?: string | undefined | null, detail?: string | undefined | null): Promise<void>

/**
 * Opens an explicit transaction. Manual mode opens one on the first
 * statement, so this is only for starting one deliberately.
 */
export declare function beginTransaction(sessionId: string): Promise<any>

/**
 * Clears the per-call session identifier for the named plugin.
 * Always called after a plugin invocation completes (success or
 * error) to prevent leakage into the next caller's context.
 */
export declare function clearCallContext(pluginId: string): Promise<void>

export declare function close(sessionId: string): Promise<void>

/** Commits the open transaction. */
export declare function commitTransaction(sessionId: string): Promise<any>

export declare function connect(config: ConnectionConfig): Promise<ConnectionHandle>

/**
 * Returns a static pong string. Smoke test that the binding loaded.
 * Connection configuration mirrored from [`plamenix_db::ConnectionConfig`].
 *
 * Field names use `camelCase` on the JS side; `serde` keeps the Rust
 * names. The two representations stay in sync because `From<JsConfig>`
 * performs the rename explicitly.
 */
export interface ConnectionConfig {
  host: string
  port: number
  database: string
  user: string
  password: string
  encryptionKey?: string
  fbclientPath?: string
  charset?: string
  encryptionRequired: boolean
  pureRust?: boolean
  embedded?: boolean
}

export interface ConnectionHandle {
  sessionId: string
}

export declare function cryptState(sessionId: string): Promise<string>

export declare function databaseStats(sessionId: string): Promise<any>

/**
 * Drops the plugin's registry entry, releasing the wasmtime Store and
 * staged bundle. Subsequent `activatePlugin` calls require a fresh
 * `loadPlugin` to re-stage.
 */
export declare function deactivatePlugin(pluginId: string): Promise<void>

export declare function describeSchema(sessionId: string): Promise<any>

/**
 * Emits `topic` to every subscribed plugin, reporting failures to the
 * supervisor.
 *
 * The single entry point for host-originated events on this edition,
 * mirroring the desktop shell's. Returns one entry per subscriber so
 * the caller can see who was reached and what the supervisor made of
 * any failure — a plugin trapping on an event must not fail the
 * request that produced it.
 * `session_id` names the session the event is about, and is what makes
 * a plugin's `db` capability usable while handling one. Without it,
 * every `db` import refuses: the host answers "the session I called
 * you for" and there is none. The desktop shell has always set this;
 * this edition did not, so a plugin granted `db.read.any` could
 * receive an event and then be denied the access the install dialog
 * told the user it had.
 *
 * Scoped to the dispatch rather than left set. The slot is per plugin
 * and this edition serves more than one caller, so a value left behind
 * would show the next request's plugin call a session belonging to
 * somebody else. Cleared on the way out whatever the dispatch did.
 */
export declare function emitEvent(topic: string, payload: string, sessionId?: string | undefined | null): Promise<any>

/**
 * Which event patterns any plugin is currently subscribed to.
 *
 * The browser asks for this so it can forward only the events
 * something actually wants. Most shell events originate in the UI, so
 * reaching a WASM plugin costs an HTTP request per event, and
 * `editor/changed` fires as the user types. With nothing subscribed,
 * the browser sends nothing.
 */
export declare function eventPatterns(): Array<string>

export declare function execute(sessionId: string, sql: string): Promise<any>

/**
 * Splits `sql` into statements, applies the per-statement row cap to
 * SELECT-like queries, executes each in order, and returns one
 * [`StatementOutcome`] per parsed statement. Aborts after the first
 * failure (mirroring the Tauri command).
 */
export declare function executeBatch(sessionId: string, sql: string): Promise<any>

/**
 * Runs the export pipeline server-side: executes one or more SELECTs,
 * then builds a CSV / JSON / SQL / XML deliverable using the shared
 * `plamenix-db::export` formatters. Returns the full text. The
 * HTTP route on top is responsible for chunked transfer to the
 * client.
 */
export declare function exportQuery(sessionId: string, format: string, csvDelimiter: string, scopeJson: string, includeDdl?: boolean | undefined | null, maxRows?: number | undefined | null): Promise<string>

export declare function fetchBlob(sessionId: string, blobId: string): Promise<string>

/**
 * Records a capability grant. Re-granting is a no-op.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function grantAdd(pluginId: string, permission: string): Promise<void>

/**
 * Capabilities granted to one plugin.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function grantList(pluginId: string): Promise<Array<string>>

/**
 * Every grant, by plugin — replayed into the plugin host at boot so a
 * plugin's approved capabilities survive a restart.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function grantListAll(): Promise<any>

/**
 * Persists an optional-permission grant on the plugin's registry
 * entry. No-op when already granted. Returns the updated activated
 * view so callers can refresh their cached UI state.
 */
export declare function grantPermission(pluginId: string, permission: string): Promise<void>

/**
 * Drops every grant for one plugin, for uninstall.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function grantPurgePlugin(pluginId: string): Promise<void>

/**
 * Withdraws a grant. Revoking one never granted is a no-op.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function grantRemove(pluginId: string, permission: string): Promise<void>

/**
 * Removes every entry for one profile, returning how many went.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function historyClear(profileId: string): Promise<number>

/**
 * Deletes one entry.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function historyDelete(id: number): Promise<boolean>

/**
 * Deletes several entries.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function historyDeleteMany(ids: Array<number>): Promise<number>

/**
 * Most recent statements for one profile, newest first.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function historyList(profileId: string, limit: number): Promise<any>

/**
 * Records one executed statement, then trims the profile to `limit`.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function historyRecord(profileId: string, sql: string, executedAt: number, durationMs: number, status: string, error?: string | undefined | null, rowsReturned?: number | undefined | null, label?: string | undefined | null, limit?: number | undefined | null): Promise<void>

/**
 * Sets or clears one entry's label.
 *
 * # Errors
 *
 * When the metadata database cannot be reached.
 */
export declare function historySetLabel(id: number, label?: string | undefined | null): Promise<boolean>

/**
 * Points the metadata store at a file. Call once, before anything else
 * here.
 *
 * Separate from opening so a failure to open surfaces on the first
 * real use with the reason attached, rather than at import time where
 * there is no request to attribute it to.
 */
export declare function initMeta(path: string, fbclientPath?: string | undefined | null): void

/**
 * Initialises the global `tracing` subscriber for the Node process.
 *
 * Idempotent: subsequent calls return `"already_initialised"`.
 *
 * One function rather than the two the split packages each exported.
 * The subscriber is process-global, so a second initialiser was never
 * doing anything except making it unclear which one mattered.
 * # Errors
 *
 * When the tracing subscriber could not be installed.
 */
export declare function initTracing(): string

/**
 * Snapshot of every currently active plugin. Cheap clone of in-memory
 * state; safe to call from any Fastify request handler.
 */
export declare function listActive(): Promise<Array<ActivatedPluginInfo>>

/**
 * Reads the host's `databases.conf` (when one is found at a known
 * install path) and returns the simple-form alias entries declared in
 * it. When no candidate file exists, returns an empty list with
 * `sourcePath = null`.
 */
export declare function listAliases(): any

/**
 * Which plugins are wired into which interceptor chain, in resolved
 * order.
 *
 * The server reads this once after boot so it only pays a round trip
 * on chains a plugin actually registered for.
 */
export declare function listInterceptors(): any

/**
 * Returns a static pong string. Smoke test that the binding loaded.
 * Loads a plugin bundle from disk. Validates the manifest, compiles
 * the WASM component, registers the plugin in the process-wide
 * registry, and returns a snapshot of staged-plugin metadata.
 */
export declare function loadPlugin(bundlePath: string): Promise<StagedPluginInfo>

/** Returns a static pong string. Smoke test that the binding loaded. */
export declare function ping(): string

export interface PingResult {
  engineVersion: string
}

export declare function pingSession(sessionId: string): Promise<PingResult>

export interface PluginLogEntry {
  level: string
  message: string
}

/**
 * Atomically reloads a plugin from its on-disk bundle without
 * requiring a shell restart. Captures the bundle path from the
 * current registry entry, deactivates the existing instance (drops
 * the wasmtime Store, freeing memory), re-stages from disk, and
 * re-activates.
 *
 * Used by `POST /api/plugins/:id/reload` to pick up bundle changes
 * (manifest edits, fresh `ui.mjs` after a plugin author's `pnpm
 * build`, etc.) without restarting the host. The reload is **not
 * transactional** — if the re-stage fails after the deactivate, the
 * plugin is left unloaded, surfaced as a normal load error to the
 * caller. The next call to `loadPlugin` (or another `reloadPlugin`
 * attempt) puts it back.
 */
export declare function reloadPlugin(pluginId: string): Promise<ActivatedPluginInfo>

/**
 * Revokes a previously granted optional permission. No-op when the
 * permission was not granted.
 */
export declare function revokePermission(pluginId: string, permission: string): Promise<void>

/**
 * Rolls back the open transaction, discarding every statement since it
 * opened — DDL included.
 */
export declare function rollbackTransaction(sessionId: string): Promise<any>

/**
 * Runs the plugin segment of an interceptor chain and returns its
 * verdict.
 *
 * An interceptor that traps, overruns its deadline, or cancels without
 * a reason is skipped and the operation proceeds. That is deliberate:
 * a third-party plugin crashing must not be able to stop someone
 * running a query against their own database. Skipped plugins are
 * reported rather than swallowed so a broken one can be attributed.
 */
export declare function runInterceptors(extensionPoint: string, contextJson: string): Promise<any>

/**
 * Sets the calling session identifier for the named plugin's next
 * invocation. Multi-tenant Fastify handlers call this before invoking
 * any plugin-side function so host imports such as
 * `db.current-session()` reflect the caller's session, not a value
 * baked in at activation time.
 *
 * Always pair with `clearCallContext` (or call `setCallContext` again
 * for the next caller); leaving stale context risks one session
 * seeing another's identifier on a subsequent unrelated call.
 */
export declare function setCallContext(pluginId: string, sessionId: string): Promise<void>

/**
 * Switches a session between autocommit and manual commit.
 *
 * `config` is the JSON form of `TxConfig`; omit it to keep the
 * session's current settings. Refused while a transaction is open, so
 * a mode change cannot silently commit or discard outstanding work.
 */
export declare function setTransactionMode(sessionId: string, mode: any, config?: any | undefined | null): Promise<any>

export interface SidebarPanelInfo {
  id: string
  label: string
  icon?: string
}

export interface StagedPluginInfo {
  id: string
  name: string
  version: string
  description?: string
  world: string
  targets: Array<string>
  restartPolicy: string
  /**
   * Absolute path to the plugin's on-disk bundle directory. Server
   * route handlers use this to resolve `<bundle>/ui.mjs` for the
   * `GET /api/plugins/:id/ui.mjs` endpoint (I2.5) without going
   * through a NAPI hop per request.
   */
  bundleDir: string
  requiredPermissions: Array<string>
  optionalPermissions: Array<string>
}

/**
 * Tries to attach with the supplied configuration, fetches the engine
 * version, then closes the session. Always resolves with a structured
 * result (no thrown error on a clean failure); the `ok` flag tells the
 * caller whether the attempt succeeded.
 */
export declare function testConnection(config: ConnectionConfig): Promise<any>

/**
 * Current transaction state. Answered from driver state without
 * touching the engine, so it is safe to poll for the age readout.
 */
export declare function transactionStatus(sessionId: string): Promise<any>
